version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: container_logica-rh-Mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logica-rh-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3307:3306

  logica-rh:
    image: ngorseck/logica-rh:0.0.1-SNAPSHOT
    container_name: container_logica-rh
    ports:
      - 8889:8889
    restart: unless-stopped
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/logica-rh-db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      spring.datasource.username: user
      spring.datasource.password: user
      JAVA_TOOL_OPTIONS: -Xss256K -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=128M -Xmx64M
    links:
      - mysql