server:
    port: 8089

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/logica-rh-db?useSSL=false&&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: user
        password: user
    application:
        name: spring-logica-rh
    liquibase:
        change-log: classpath:/db/changelog/changelog-master.xml
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8080/realms/logica-rh/protocol/openid-connect/certs
                    #URL : http://localhost:8080/realms/logica-rh/.well-known/openid-configuration
    #modification pour le caching
    redis:
        host: localhost
        port: 6379
        cache:
            redis:
                cache-null-values: false
                time-to-live: 40000
            type: redis
springdoc:
    api-docs:
        path: /api-docs

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,wavefront
    info:
        env:
            enabled: true

    endpoint:
      health:
        show-details: ALWAYS

    health:
        redis:
          enabled: true #modification pour redis == false a true
        probes:
            enabled: true

info:
    application:
        name: spring-logica-rh
        version: '@project.version@'

wavefront:
    application:
        name: spring-logica-rh

logging:
    level:
        org:
            springframework:
                web: DEBUG
    file:
        name: logs/mylog.log
        #name: /Users/macbookair/Documents/IJProjects/2022/Spring/2022/Canada/coach-mamadou-lamine/logica-rh/logs/mylog.log
